register/register/campus_admin/urls.py
from django.conf.urls import url
from . import views

app_name = 'campus_admin'

# For char .+ whereas for integer \d+
urlpatterns=[

    url(r'^$', views.index, name='index'),

    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/(?P<pk3>.+)/success/$', views.success_result,
        name='success_result'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/success/$', views.success_fee_receipt,
        name='success_fee_receipt'),

    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/course_list/$', views.course_list,
        name='course_list'),
    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/$', views.result_view, name='result_view'),
    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/view/$', views.final_result_view, name='final_result_view'),

    # url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/add_grade/$',views.add_grade,name='add_grade'),
    # url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/(?P<pk3>.+)/result_update/$', views.result_update,
    #   name='result_update'),
    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/(?P<pk3>.+)/result_add/$', views.result_add,
        name='result_add'),
    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/$', views.sem_view_result, name='sem_view_result'),
    url(r'^result/(?P<pk4>.+)/(?P<pk>.+)/$', views.result_base, name='result_base'),
    url(r'^result/add_course/$', views.add_course, name='add_course'),
    url(r'^add_faculty/$', views.add_faculty, name='add_faculty'),
    url(r'^success/$', views.success, name='success'),
    # url(r'^result/(?P<pk5>.+)/add_semester/$',views.add_semester,name='add_semester'),
    url(r'^result/$', views.result, name='result'),
    url(r'^registration/', views.registration, name='registration'),

    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/$', views.fee_receipt_view,
        name='fee_receipt_view'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/view/$', views.final_fee_receipt_view,
        name='final_fee_receipt_view'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/fee_receipt_add/$', views.fee_receipt_add,
        name='fee_receipt_add'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/$', views.sem_view_fee, name='sem_view_fee'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk>.+)/$', views.fee_receipt_base, name='fee_receipt_base'),
    url(r'^fee_receipt/$', views.fee_receipt, name='fee_receipt'),

]

register/register/qa/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.QuestionIndexView.as_view(), name='qa_index'),

    url(r'^question/(?P<pk>\d+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/(?P<pk>\d+)/(?P<slug>[-_\w]+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/answer/(?P<answer_id>\d+)/$',
        views.AnswerQuestionView.as_view(), name='qa_answer_question'),

    url(r'^question/close/(?P<question_id>\d+)/$',
        views.CloseQuestionView.as_view(), name='qa_close_question'),

    url(r'^new-question/$', views.CreateQuestionView.as_view(),
        name='qa_create_question'),

    url(r'^edit-question/(?P<question_id>\d+)/$',
        views.UpdateQuestionView.as_view(),
        name='qa_update_question'),

    url(r'^answer/(?P<question_id>\d+)/$',
        views.CreateAnswerView.as_view(), name='qa_create_answer'),

    url(r'^answer/edit/(?P<answer_id>\d+)/$',
        views.UpdateAnswerView.as_view(), name='qa_update_answer'),



    url(r'^comment-answer/(?P<answer_id>\d+)/$',
        views.CreateAnswerCommentView.as_view(),
        name='qa_create_answer_comment'),

    url(r'^comment-question/(?P<question_id>\d+)/$',
        views.CreateQuestionCommentView.as_view(),
        name='qa_create_question_comment'),

    url(r'^comment-question/edit/(?P<comment_id>\d+)/$',
        views.UpdateQuestionCommentView.as_view(),
        name='qa_update_question_comment'),

    url(r'^comment-answer/edit/(?P<comment_id>\d+)/$',
        views.UpdateAnswerCommentView.as_view(),
        name='qa_update_answer_comment'),

    url(r'^search/$', views.QuestionsSearchView.as_view(), name='qa_search'),

    url(r'^tag/(?P<tag>[-\w]+)/$',
        views.QuestionsByTagView.as_view(), name='qa_tag'),

    url(r'^markdown/', include('django_markdown.urls')),

    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),

]

register/register/qaforum/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.QaQuestionIndexView.as_view(), name='qaforum_index'),

    url(r'^question/(?P<pk>\d+)/$',
        views.QaQuestionDetailView.as_view(), name='qaforum_detail'),

    url(r'^question/(?P<pk>\d+)/(?P<slug>[-_\w]+)/$',
        views.QaQuestionDetailView.as_view(), name='qaforum_detail'),

    url(r'^question/answer/(?P<answer_id>\d+)/$',
        views.QaAnswerQuestionView.as_view(), name='qaforum_answer_question'),

    url(r'^question/close/(?P<question_id>\d+)/$',
        views.QaCloseQuestionView.as_view(), name='qaforum_close_question'),

    url(r'^new-question/$', views.QaCreateQuestionView.as_view(),
        name='qaforum_create_question'),

    url(r'^edit-question/(?P<question_id>\d+)/$',
        views.QaUpdateQuestionView.as_view(),
        name='qaforum_update_question'),

    url(r'^answer/(?P<question_id>\d+)/$',
        views.QaCreateAnswerView.as_view(), name='qaforum_create_answer'),

    url(r'^answer/edit/(?P<answer_id>\d+)/$',
        views.QaUpdateAnswerView.as_view(), name='qaforum_update_answer'),



    url(r'^comment-answer/(?P<answer_id>\d+)/$',
        views.QaCreateAnswerCommentView.as_view(),
        name='qaforum_create_answer_comment'),

    url(r'^comment-question/(?P<question_id>\d+)/$',
        views.QaCreateQuestionCommentView.as_view(),
        name='qaforum_create_question_comment'),

    url(r'^comment-question/edit/(?P<comment_id>\d+)/$',
        views.QaUpdateQuestionCommentView.as_view(),
        name='qaforum_update_question_comment'),

    url(r'^comment-answer/edit/(?P<comment_id>\d+)/$',
        views.QaUpdateAnswerCommentView.as_view(),
        name='qaforum_update_answer_comment'),

    url(r'^search/$', views.QaQuestionsSearchView.as_view(), name='qaforum_search'),

    url(r'^tag/(?P<tag>[-\w]+)/$',
        views.QaQuestionsByTagView.as_view(), name='qaforum_tag'),

    url(r'hitcount/', include('hitcount.urls', namespace='qahitcount')),

]

register/register/student/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.views.generic import TemplateView

app_name = 'student'
from .views import (student_home_page, StudentCourseList,
                    student_course_detail_view, AnnouncementView,
                    student_assignment_files_list, course_registration_view,
                    classmates, view_profile, edit_profile,
                    files_list)

urlpatterns = [
    url(r'^$', student_home_page, name='student_home_page'),
    url(r'^courses/$', StudentCourseList.as_view(), name='student_course_list'),
    # url(r'^forum/', include('register.qaforum.urls', namespace='qaforum')),
    url(r'^classmates/$', classmates, name = 'view_classmates'),
    url(r'^profile/edit/$', edit_profile, name = 'edit_profile'),
    url(r'^profile/$', view_profile, name = 'view_profile'),
    url(r'^profile/(?P<pk>\w+)/$', view_profile, name = 'view_profile_with_pk'),

    url(r'^courses/registration/$', course_registration_view, name='course_registration_view'),
    url(r'^courses/(?P<course_no>.+)/course-material/files_list/$', files_list, name='course_material_files_list'),
    url(r'^courses/(?P<course_no>.+)/announcements/view/$', AnnouncementView.as_view(), name='announcement_view'),
    url(r'^courses/(?P<course_no>.+)/assignment/view/$', student_assignment_files_list, name='student_assignment_files_list'),
    url(r'^courses/(?P<course_no>.+)/$', student_course_detail_view, name='student_course_detail_view'),
]

register/register/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

from . import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from registration.backends.hmac.views import RegistrationView
from .forms import NewRegistrationForm
from register.course.views import download, assignment_download, assignment_submission_download

urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^campus-admin/', include('register.campus_admin.urls', namespace='campus_admin')),
    url(r'^faculty/course/', include('register.course.urls', namespace='course')),
    # url(r'^faculty/course/(?P<pk>.+)/assignment/', include('register.assignment.urls', namespace='assignment')),
    url(r'^faculty/', include('register.faculty.urls', namespace='faculty')),
    url(r'^student/courses/(?P<course_no>.+)/forum/', include('register.qa.urls', namespace='qa')),
    url(r'^faculty/courses/(?P<course_no>.+)/forum/', include('register.qa.urls', namespace='facultyqa')),
    url(r'^forum/', include('register.qaforum.urls', namespace='qaforum')),
    url(r'^student/', include('register.student.urls', namespace='student')),
    url(r'^announcements/', include('register.announcements.urls', namespace='announcements')),
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=NewRegistrationForm), name='registration_register'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^download/course-material/(?P<file_name>.+)$', download, name='course_material_download'),
    url(r'^download/assignment-material/(?P<file_name>.+)$', assignment_download, name='course_material_download'),
    url(r'^download/assignment-submission/(?P<file_name>.+)$', assignment_submission_download, name='course_material_download'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
    urlpatterns += [
        url(r'^staticfiles/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

register/register/student/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from register.course.models import AssignmentMaterial
from register.course.models import course, OfferedIn
from django.core.urlresolvers import reverse
from django.dispatch import receiver


class student(models.Model):
    course_no = models.ManyToManyField(course)
    user_student= models.ForeignKey(User, null=True)
    student_id = models.CharField(max_length=20, null=True, unique=True)
    program = models.CharField(max_length=20, null=True)
    batch = models.CharField(max_length=20, null=True)

    @classmethod
    def create(cls, user_student, student_id, program, batch):
        student = cls(user_student=user_student, student_id=student_id, program=program, batch=batch)
        return student

    def __str__(self):
        return self.student_id

class AssignmentSubmission(models.Model):
    assignment = models.ManyToManyField(AssignmentMaterial)
    file = models.FileField(upload_to='assignment-submission/')
    student = models.ForeignKey(User, null=True)
    uploaded_at = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.file.name

class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().order_by('phone')

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    description = models.CharField(max_length=100, default='')
    image = models.ImageField(null=True, blank=True, height_field='height_field', width_field='width_field')
    height_field = models.IntegerField(default=1944)
    width_field = models.IntegerField(default=2592)
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    student_id = models.IntegerField(default=0)
    date_of_birth = models.DateField(null=True, blank=True)
    email = models.CharField(max_length=100, default='')
    order_byPhone = UserProfileManager()

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('student:view_profile', kwargs={'course_no': self.course_no})

def create_profile( sender, **kwargs):
    user = kwargs['instance']
    if kwargs['created']:
        user_profile = UserProfile(user=user)
        user_profile.save()

post_save.connect(create_profile, sender = User)
#
# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.userprofile.save()

register/register/student/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import AssignmentSubmission, UserProfile

class AssignmentSubmissionForm(ModelForm):
    # def is_valid(self):
    #     valid = super(AssignmentSubmissionForm, self).is_valid()
    #     if not valid:
    #         return valid

    class Meta:
        model = AssignmentSubmission
        fields = ('file', )

class UserForm(ModelForm):

    class Meta:
        model = User
        fields = ('username','first_name','last_name' )


class EditProfileForm(ModelForm):

    class Meta:
        model = UserProfile
        fields = ('date_of_birth','email','city','phone','image' )

register/register/student/templates/student_course_detail_view.html
{% extends 'student_view.html' %}

{% load static %}
{% block extend %}
<style>
.wraper {
  position: absolute;
  top: 30%;
  left: 48%;
  margin: 0 auto -100px; /*Allow for footer height*/
  height: auto !important; /*Cause footer to stick to bottom in IE 6*/
  margin-left: -25% ;
  text-align: center;
}
.wrap {
  min-height: 100px;
  height: auto;
  height: ;
  display: -webkit-box;
  display: -ms-flexbox;
  display: box;
  display: flex;
}
.sidenav {
    min-height: 92%;
    height: auto;
    width: 0;
    position: absolute;
    z-index: 1;
    top: 168px;
    left: 0;
    background-color: #00000;
    overflow-x: hidden;
    transition: 0.5s;
    padding-top: 60px;
}

.sidenav a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 25px;
    color: #0f6c6b;
    display: block;
    transition: 0.3s;
}

.sidenav a:hover {
    color: #a3a948;
}

.sidenav .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
}

#main {
    transition: margin-left .5s;
    padding: 16px;
}
.cont{

    text-align: center;
}
</style>

<body class="wrap">
        <main1>
            <aside >
                  <div id="mySidenav" class="sidenav">
                    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

                    <a href="{% url 'student:course_material_files_list' course_no=course_no %}">Course Material</a>
                    <a href="{% url 'student:student_assignment_files_list' course_no=course_no %}">Assignments</a>
                    <a href="{% url 'qa:qa_index' course_no=course_no %}">Discusion Forum</a>
                  </div>

                  <div id="main" >
                    <div class="mainblock">


                      <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;

                        {% block bar %}
                          {{course.courseNo.courseName}}
                        {% endblock bar %}
                      </span>

                      {% block student_content %}
                            <div class="cont">
                          <h1>Dear {{ user.username }}, Welcome to course {{ course_no }}</h1>
                                <hr>
                            <h3>This is place where you can learn beyond your boundaries.</h3>
                            <hr>
                           </div>
                      {% endblock student_content %}

                    </div>
                  </div>
                </div>
            </aside>
        </main1>

</body>


<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.getElementById("main").style.marginLeft= "0";
}
</script>
{% endblock %}

register/register/student/templates/student_course_view.html
{% extends "student_view.html" %}

{% block extend %}

<ul>
	{% for obj in object_list %}
		<li><a href="{% url 'student:student_course_detail_view' course_no=obj %}">{{ obj }}</a><br/>
	{% endfor %}
</ul>
{% endblock %}

register/register/student/templates/student_home_page.html
{% extends 'base.html' %}

{% block content %}
<header>
    <nav>
    <div class="navbar navbar-inverse navbar-custom" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li> <a href="/student/" >Home </a></li>
			<li> <a href="{% url 'campus_admin:final_fee_receipt_view' pk4=stud.program  pk1=stud.batch pk=stud.student_id %}" >Fee Details</a> </li>
			<li> <a href="{% url 'campus_admin:final_result_view' pk4=stud.program  pk1=stud.batch pk=stud.student_id %}" >Results </a> </li>
			<li> <a href="{% url 'student:view_classmates' %}">Classmates </a> </li>
			<li> <a href="{% url 'student:view_profile' %}" >Profile </a> </li>
      <li> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
              <ul class="dropdown-menu multi-level">
                <li><a href="{% url 'student:edit_profile' %}">Edit Profile</a></li>
                <li><a href="{% url 'auth_password_change' %}">Reset Password</a></li>
                <li><a href="{% url 'auth_logout' %}">Logout</a></li>

              </ul>
            </li>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </div>

  </nav>
</header>

<style type="text/css">



  span
{
    line-height: normal;
    display:inline-block;
    vertical-align: middle;
}

.rectangles{
padding-top:20px;
padding-bottom:10px;
}
.rectangles .rectangle1 {
    border-radius: 10px;
    display: inline-block;
    margin-bottom: 30px;
    margin-right: 5px;
    width: 290px;
    height: 100px;
    border: 2px solid #a3a948;
    background-color: #0f6c6b;
    padding: 18px 5px 5px 5px;
    position: relative;
	line-height: normal;
    display:inline-block;
    vertical-align: middle;


}
.rectangles .rectangle {
    border-radius: 10px;
    display: inline-block;
    margin-bottom: 30px;
    margin-right: 5px;
    width: 290px;
    height: 100px;
    border: 2px solid #0f6c6b;
    background-color: #2aafb4;
    padding: 18px 5px 5px 5px;
    position: relative;
	line-height: normal;
    display:inline-block;
    vertical-align: middle;


}
.rectangles .rectangle .circle {
  background: #0f6c6b;
  border-radius: 100%;
     border: 2px solid #a3a948;
  height: 60px;
  width: 60px;
  position: absolute;
  top: 20px;
  left: 20px;
    text-align:center;
	line-height:50px;
}
    .cfo{
        padding-left:40px;
        padding-top:20px;
        color:white;
    }
	.cfo1{
        padding-left:35px;
        padding-top:20px;
       padding-right:35px;
    }
</style>
<style type="text/css">
.flex-container1{
	width: 100%;
	min-height: 500px;
	margin: 0 auto;
	display: -webkit-flex; /* Safari */
	display: flex; /* Standard syntax */
}
.flex-container1 .column{
	padding: 10px;
	background: #f7f7f7;
	-webkit-flex: 1; /* Safari */
	-ms-flex: 1; /* IE 10 */
	flex: 1; /* Standard syntax */
}
.flex-container1 .column.bg-alt{
	background: #b4bac0;
}
</style>
<style>


.wrap {
	padding-top:10px;
  height: 60vh;
  display: -webkit-box;
  display: -ms-flexbox;
  display: box;
  display: flex;
}
main1 {
  -webkit-box-flex: 1;
  -o-box-flex: 1;
  box-flex: 1;
  -ms-flex: 1;
  flex: 1;
  display: -webkit-box;
  display: -ms-flexbox;
  display: box;
  display: flex;
  padding-bottom:20px;
  padding-top:20px;
}
@media (max-width:   800px) {
  main1 {
    -webkit-box-orient: vertical;
    -o-box-orient: vertical;
    -ms-flex-direction: column;
    flex-direction: column;
  }
}
aside,
article {
  overflow-y: scroll;
  padding: 2em;
}
aside {
  -webkit-box-flex: 1;
  -o-box-flex: 1;
  box-flex: 1;
  -ms-flex: 1;
  flex: 1;
  background: #FFFFFF;
}
article {
  -webkit-box-flex: 2;
  -o-box-flex: 2;
  box-flex: 2;
  -ms-flex: 2;
  flex: 2;
 background: #F5F5F5;
}
h1 {
  margin-top: 0;
}
        </style>


<!--<div class="flex-container1">-->
        <!--<div class="column">-->
                <!--<div class="wrap">-->
                    <!--<main1>-->
                        <!--<aside >-->
                            <!--<div class="wraper">-->
                                <!--{% for course in student_courses %}-->
                                    <!--<a href="{% url 'student:student_course_detail_view' course_no=course  %}" class="button button&#45;&#45;ghost button&#45;&#45;ghost&#45;&#45;green">{{ course }}</a>-->
                                <!--{% endfor %}-->
                                    <!--<a href="/forum" class="button button&#45;&#45;ghost button&#45;&#45;ghost&#45;&#45;green">Forum</a>-->
                            <!--</div>-->
                        <!--</aside>-->
                    <!--</main1>-->
                <!--</div>-->
		<!--</div>-->
        <!--<div class="column bg-alt">-->
		<!--<div class="wrap">-->
            <!--<main1>-->
                <!--<article>-->
                    <!--<h1 style="text-align:center;text-color:#ff0000">Announcements</h1>-->
                    <!--{% for announcement in announcement_in_courses %}-->
                        <!--<p>{{ forloop.counter }}. {{ announcement.announcement }} - {{ announcement.announcementUser }}, {{ announcement.uploaded_at }}</p>-->
                    <!--{% endfor %}-->
                <!--</article>-->
            <!--</main1>-->
        <!--</div>-->
		<!--</div>-->
<!--</div>-->
<div class="conta">
 <div class="flex-container">
        <div class="column">
         <div class="container">
             <div class="row">
			 <div class="col-sm-4 col-md-4 col-lg-4" style="   margin-top:30px">
        <div class="rectangles">

                 {% for course in student_courses %}
                    <div class="rectangle">
                         <div class="circle">
						   <span style="color:white">{{ course }}</span>
						 </div>
                                <p class="cfo" style="font-size:15px" ><a href="{% url 'student:student_course_detail_view' course_no=course  %}"><font color="#FFFFFF";font-size="14px"> {{ course.course_name }}</font></a></p>
					</div><br>

                {% endfor %}



                    <div class="rectangle">

                                <p  style="font-size:20px;padding-top: 10px" ><a href="/forum"><font color="#FFFFFF";font-size="14px">Discussion Forum</font></a></p>
                   </div><br>

    </div>
             </div>

	<div class="col-sm-8 col-md-8 col-log-8" style="background-color:#0f6c6b;margin-top:50px;margin-bottom:10px">
	<h1 style="color:white">Announcements</h1>
        <div class="wrap">
            <main1>
                <article>
                        {% for announcement in announcement_in_courses %}
                            <li>{{ announcement.announcement }} - {{ announcement.announcementUser }}, {{ announcement.uploaded_at }}</li>
                        {% endfor %}
                </article>
            </main1>
        </div>
           </div    >
	         </div>
         </div>
      </div>
</div>
    </div>
{% comment %}
{% if user.is_authenticated %}
    <p><strong>Dear {{ user.username }} student, glad to have you here!</strong></p>
    <p>This is IIITV Ecampus</p>
    <p><a align="center" href="{% url 'student:student_course_list' %}">Courses</a></p>
    <p><a href="{% url 'qaforum:qaforum_index' %}">Forum</a></p>
{% endif %}
{% endcomment %}
{% endblock %}

register/register/student/templates/student_view.html
{% extends 'base.html' %}
{% block content %}
<header>
    <nav>
    <div class="navbar navbar-inverse navbar-custom" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li> <a href="/student/" >Home </a></li>
			<li> <a href="{% url 'campus_admin:final_fee_receipt_view' pk4=pk4  pk1=pk1 pk=pk %}" >Fee Details</a> </li>
			<li> <a href="{% url 'campus_admin:final_result_view' pk4=pk4  pk1=pk1 pk=pk %}" >Results </a> </li>

			<li> <a href="{% url 'student:view_classmates' %}">Classmates </a> </li>
			<li> <a href="{% url 'student:view_profile' %}" >Profile </a> </li>
      <li> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
              <ul class="dropdown-menu multi-level">
                <li><a href="{% url 'student:edit_profile' %}">Edit Profile</a></li>
                <li><a href="{% url 'auth_password_change' %}">Reset Password</a></li>
                <li><a href="{% url 'auth_logout' %}">Logout</a></li>

              </ul>
            </li>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </div>

  </nav>
</header>
{% block extend %}
{% endblock extend %}
{% endblock content %}