register/register/campus_admin/urls.py
from django.conf.urls import url
from . import views

app_name = 'campus_admin'

# For char .+ whereas for integer \d+
urlpatterns=[

    url(r'^$', views.index, name='index'),

    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/(?P<pk3>.+)/success/$', views.success_result,
        name='success_result'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/success/$', views.success_fee_receipt,
        name='success_fee_receipt'),

    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/course_list/$', views.course_list,
        name='course_list'),
    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/$', views.result_view, name='result_view'),
    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/view/$', views.final_result_view, name='final_result_view'),

    # url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/add_grade/$',views.add_grade,name='add_grade'),
    # url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/(?P<pk3>.+)/result_update/$', views.result_update,
    #   name='result_update'),
    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/(?P<pk3>.+)/result_add/$', views.result_add,
        name='result_add'),
    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/$', views.sem_view_result, name='sem_view_result'),
    url(r'^result/(?P<pk4>.+)/(?P<pk>.+)/$', views.result_base, name='result_base'),
    url(r'^result/add_course/$', views.add_course, name='add_course'),
    url(r'^add_faculty/$', views.add_faculty, name='add_faculty'),
    url(r'^success/$', views.success, name='success'),
    # url(r'^result/(?P<pk5>.+)/add_semester/$',views.add_semester,name='add_semester'),
    url(r'^result/$', views.result, name='result'),
    url(r'^registration/', views.registration, name='registration'),

    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/$', views.fee_receipt_view,
        name='fee_receipt_view'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/view/$', views.final_fee_receipt_view,
        name='final_fee_receipt_view'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/fee_receipt_add/$', views.fee_receipt_add,
        name='fee_receipt_add'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/$', views.sem_view_fee, name='sem_view_fee'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk>.+)/$', views.fee_receipt_base, name='fee_receipt_base'),
    url(r'^fee_receipt/$', views.fee_receipt, name='fee_receipt'),

]

register/register/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

from . import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from registration.backends.hmac.views import RegistrationView
from .forms import NewRegistrationForm
from register.course.views import download, assignment_download, assignment_submission_download

urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^campus-admin/', include('register.campus_admin.urls', namespace='campus_admin')),
    url(r'^faculty/course/', include('register.course.urls', namespace='course')),
    # url(r'^faculty/course/(?P<pk>.+)/assignment/', include('register.assignment.urls', namespace='assignment')),
    url(r'^faculty/', include('register.faculty.urls', namespace='faculty')),
    url(r'^student/courses/(?P<course_no>.+)/forum/', include('register.qa.urls', namespace='qa')),
    url(r'^faculty/courses/(?P<course_no>.+)/forum/', include('register.qa.urls', namespace='facultyqa')),
    url(r'^forum/', include('register.qaforum.urls', namespace='qaforum')),
    url(r'^student/', include('register.student.urls', namespace='student')),
    url(r'^announcements/', include('register.announcements.urls', namespace='announcements')),
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=NewRegistrationForm), name='registration_register'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^download/course-material/(?P<file_name>.+)$', download, name='course_material_download'),
    url(r'^download/assignment-material/(?P<file_name>.+)$', assignment_download, name='course_material_download'),
    url(r'^download/assignment-submission/(?P<file_name>.+)$', assignment_submission_download, name='course_material_download'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
    urlpatterns += [
        url(r'^staticfiles/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

register/register/campus_admin/models.py
from django.db import models
from register.course.models import OfferedIn, course
from register.student.models import student

class Courses(models.Model):
    courseNo = models.CharField(max_length = 10, default = '',primary_key = True)
    courseName = models.CharField(max_length = 100, default = '')
    credits = models.IntegerField(default = 0)

    def __str__(self):
        return self.courseNo

class Registers(models.Model):
    studentId = models.ForeignKey(student,related_name='student_id+',null=True)
    acadYear = models.ForeignKey(OfferedIn,related_name='acadYear+',null=True)
    semesterNo = models.ForeignKey(OfferedIn, related_name='semester+', null=True)
    courseNo = models.ForeignKey(course, related_name='courseNo+', null=True)
    grade = models.CharField(max_length=4,null=True,blank=True)

    class Meta:
        unique_together = (('acadYear','semesterNo','courseNo','studentId'),)
    def __str__(self):
        return str(self.semesterNo)+"-"+self.courseNo.courseNo

class Offers(models.Model):
    acadYear = models.ForeignKey(OfferedIn, related_name='acadYear+', null=True)
    semesterNo = models.ForeignKey(OfferedIn, related_name='semester+', null=True)
    courseNo = models.ForeignKey(course, related_name='courseNo+', null=True)

    class Meta:
        unique_together = (('acadYear','semesterNo','courseNo'),)


class FeeReceipt(models.Model):
    studentId = models.ForeignKey(student,related_name='student_id+',null=False,default="0")
    acadYear = models.ForeignKey(OfferedIn, related_name='acadYear+', null=True)
    semesterNo = models.ForeignKey(OfferedIn, related_name='semester+', null=True)
    receiptId = models.CharField(max_length=30,null=False,blank=True,default="0")
    status = models.CharField(max_length=50,null=False,blank=True,default='Not Paid')

    class Meta:
        unique_together = (('acadYear','semesterNo','studentId'),)


class Result(models.Model):
    studentId = models.ForeignKey(student, related_name='student_id+')
    acadYear = models.ForeignKey(OfferedIn, null=True, related_name='acadYear+')
    semesterNo = models.ForeignKey(OfferedIn, null=True, related_name='semester+')
    SPI = models.FloatField(default='',blank=True,null=True)

register/register/campus_admin/views.py
import datetime
from django.shortcuts import render,get_object_or_404,redirect
from .models import Registers,FeeReceipt,Result
from register.student.models import student
from register.course.models import OfferedIn,course
from .forms import RegistersForm,FeeReceiptForm,CoursesForm,FacultyForm
from django.http import HttpResponse
import math
from django.db.models import Max,Min


def index(request):
    template = 'campus_admin/homepage.html'
    return render(request, template)


def registration(request):
    return  HttpResponse('<p> Nothing to Show </p>')


def result(request):

    # student = Student.objects.get(studentId='201552078')
    # year = student.batch
    # program = student.programName
    # present_acadYear = student.acadYear.acadYear
    # present_semester = student.semesterNo.semesterNo
    # args = {'present_acadYear':present_acadYear,'present_semester':present_semester}

    all_batches = student.objects.order_by('batch').values('batch').distinct()
    # batches = tuple(all_batches)
    # length = len(batches)
    # number = len(batches)
    # for i in all_batches:
    #     print(i)
    args = {'batches': all_batches}
    return render(request, 'campus_admin/result_base.html', args)


def fee_receipt(request):

    # student = Student.objects.get(studentId='201552078')
    # year = student.batch
    # program = student.programName
    # present_acadYear = student.acadYear.acadYear
    # present_semester = student.semesterNo.semesterNo
    # args = {'present_acadYear':present_acadYear,'present_semester':present_semester}

     # dictlist = []

    all_batches = student.objects.order_by('batch').values('batch').distinct()
    print(all_batches)
    # for key,value in all_batches.items():
     #   temp = [key,value]
      #  dictlist.append(temp)

    # length = len(batches)
    # number = len(batches)
    # for i in all_batches:
    #     print(i)
    args = {'batches':all_batches}
    return render(request, 'campus_admin/fee_receipt_base.html', args)


def result_base(request,pk,pk4):
    student1 = student.objects.filter(batch=pk, program=pk4)
    args = {'student':student1,'pk4':pk4}
    return render(request, 'campus_admin/student_View_result.html', args)


def fee_receipt_base(request,pk,pk4):
    # print(student.objects.filter(batch=pk, program=pk4))
    student1 = student.objects.filter(batch=pk, program=pk4)
    print(student1)
    args = {'student':student1,'pk4':pk4}
    return render(request, 'campus_admin/student_View_fee.html', args)


def sem_view_result(request,pk,pk1,pk4):
    current_student = student.objects.get(student_id=pk)
    current_semester = datetime.datetime.now().year - int(current_student.batch)
    current_semester = current_semester * 2 + 1
    #  max = int(max) - 1
    # print(value)
    return render(request, 'campus_admin/semester_View_result.html', {'pk': pk, 'pk1': pk1, 'pk4': pk4, 'value': current_semester})


def sem_view_fee(request,pk,pk1,pk4):
    # print(pk)
    # print(pk1)
    # print(pk4)
    current_student = student.objects.get(student_id=pk)
    # print(current_student)
    current_semester = datetime.datetime.now().year - int(current_student.batch)
    current_semester = current_semester * 2 + 1
    # print(current_semester)
    #  max = int(max) - 1
    #  print(value)
    return render(request, 'campus_admin/semester_View_fee.html',
                  {'pk': pk, 'pk1': pk1, 'pk4': pk4, 'pk2': current_semester})


def course_list(request,pk,pk1,pk2,pk4):
   # print(pk2)
   try:
        stud = student.objects.get(student_id=pk)
        sem = OfferedIn.objects.get(semester=pk2)
        students = Registers.objects.filter(studentId=stud,semesterNo=sem)
   except:
        students = None
   args = {'students':students,'pk1':pk1,'pk2':pk2,'pk4':pk4}
   return render(request,'campus_admin/course_list.html',args)

'''
def result_add(request,pk,pk1,pk2,pk3,pk4):
    if request.method == 'POST':
        form = ResultForm(request.POST)
        if form.is_valid():
            grade = request.POST.get('grade')
            # print(grade)
            Registers.objects.filter(studentId=pk, courseNo=pk3).update(grade=grade)
           # print(form.instance.grade)
           # form.instance.grade = Registers.objects.filter(studentId=pk, courseNo=pk1)
        # return redirect('campus_admin:success')
    else:
        form = ResultForm()
    return render(request,'campus_admin/result_add.html',{'form':form})
'''


def add_faculty(request):

    if request.method == "POST":
        form = FacultyForm(request.POST)

        if form.is_valid():
            temp = form.save()
            return redirect('campus_admin:success')
    else:
        form = FacultyForm

    return render(request,'campus_admin/faculty_add.html',{'form':form})


def success(request):
    return render(request,'campus_admin/success.html')


def add_course(request):

    if request.method == "POST":
        form = CoursesForm(request.POST or None)
        # print(form.assigned_to)
        if form.is_valid():
            temp=form.save()
            return redirect('campus_admin:success')
    else:
        form = CoursesForm
    return render(request,'campus_admin/courses_add.html',{'form':form})


def result_add(request,pk,pk1,pk2,pk3,pk4):
    stud = student.objects.get(student_id=pk)
    sem = OfferedIn.objects.get(semester=pk2)
    corse = course.objects.get(courseNo=pk3)
    students = Registers.objects.get(studentId=stud,courseNo=corse,semesterNo=sem)
    form = RegistersForm(request.POST or None,instance=students)

    if form.is_valid():
        temp = form.save(commit=False)
        grade = request.POST.get('grade')
        Registers.objects.filter(studentId=stud, courseNo=corse).update(grade=grade)
        # temp.save()
        return redirect('campus_admin:success_result',pk=pk,pk4=pk4,pk1=pk1,pk2=pk2,pk3=pk3)

    return render(request, 'campus_admin/result_add.html', {'form': form})


def success_result(request, pk4, pk1, pk, pk2, pk3):

    args = {'pk4':pk4 ,'pk1':pk1}
    return render(request, 'campus_admin/successful_result_update.html', args)


def success_fee_receipt(request, pk4, pk1, pk, pk2):

    args = {'pk4': pk4,'pk1':pk1}
    return render(request, 'campus_admin/successful_fee_receipt_update.html', args)


def fee_receipt_add(request,pk,pk1,pk2,pk4):
    sem = OfferedIn.objects.get(semester=pk2)
    current_student = student.objects.get(student_id=pk)
    form = FeeReceiptForm(request.POST or None, instance=current_student)

    if form.is_valid():
        temp = form.save(commit=False)
        data = request.POST.get('receiptId')
        data1 = request.POST.get('status')

        FeeReceipt.objects.filter(studentId=current_student,semesterNo=sem).update(receiptId=data)
        FeeReceipt.objects.filter(studentId=current_student,semesterNo=sem).update(status=data1)
        return redirect('campus_admin:success_fee_receipt', pk=pk, pk4=pk4, pk1=pk1, pk2=pk2)

    #print(form.errors)
    return render(request,'campus_admin/fee_receipt_add.html',{'form':form})

'''
def add_grade(request,pk,pk1,pk2,pk4):
    student = get_object_or_404(Result,studentId=pk ,semesterNo=pk2,acadYear__acadYear=pk1)
    form = ResultForm(request.POST or None, instance=student)
    if form.is_valid():
        temp = form.save(commit=False)
        data = request.POST.get('SPI')
        Result.objects.filter(studentId=pk,acadYear__acadYear=pk1,semesterNo=pk2).update(SPI=data)
    return render(request,'campus_admin/add_grade.html',{'form':form})
'''


def final_result_view(request,pk,pk1,pk4):

    current_student = student.objects.get(student_id=pk)
    temp = Registers.objects.filter(studentId=current_student)
    semNo = temp.order_by('semesterNo').values('semesterNo').distinct()
    year = request.user.email[0:4]
    temp = int(datetime.datetime.now().year) - int(year)
    temp = 2 * temp
    if datetime.datetime.now().month >= 8:
        temp = temp + 1
    temp = temp-1
   #  max = int(max) - 1
   #  print(value)
    return render(request,'campus_admin/final_result_view.html',{'pk':pk,'pk1':pk1,'pk4':pk4,'value':temp})


def final_fee_receipt_view(request,pk,pk1,pk4):

    current_student = student.objects.get(student_id=pk)
    temp = FeeReceipt.objects.filter(studentId=current_student)
    semNo = temp.order_by('semesterNo').values('semesterNo').distinct()
    year = request.user.email[0:4]
    temp = int(datetime.datetime.now().year) - int(year)
    temp = 2*temp
    if datetime.datetime.now().month >= 8:
        temp = temp+1
    #  max = int(max) - 1
    #  print(value)
    return render(request, 'campus_admin/final_fee_receipt_view.html', {'pk': pk, 'pk1': pk1, 'pk4': pk4, 'value': temp})


def result_view(request,pk,pk1,pk2,pk4):

    sem = OfferedIn.objects.get(semester=pk2)
    #print(sem)
    current_student = student.objects.get(student_id=pk)
    temporary = Result.objects.get(studentId=current_student, semesterNo=sem)
    course = Registers.objects.filter(studentId=current_student, semesterNo=sem)
    total = 0
    CPI = 0.0

    if temporary.SPI == None:

        for c in course:
            total = total + c.courseNo.credits
        SPI = (math.ceil(calculate_points(current_student,sem,total)*100)/100)
        # print(SPI)
        temporary = Result.objects.get(studentId=current_student,semesterNo=sem)
        temporary.SPI = SPI
        temporary.save()
        # print(SPI,pk2)

    else:
        SPI = temporary.SPI
    # print(temp)

    temp = int(pk2) - 1

    if pk2 == '1':
        CPI = SPI
    else:
        while temp > 0 :
            temporary = Result.objects.get(studentId=current_student, semesterNo=sem)
            CPI = SPI+temporary.SPI
          #  print(CPI)
            temp = temp - 1

        CPI = CPI/int(pk2)
        CPI = (math.ceil(CPI * 100) / 100)
    iterate = int(pk2)-1
    # print(CPI,SPI)

register/register/campus_admin/templates/campus_admin/course_list.html
{% extends 'campus_admin/base.html' %}


{% block body %}
    <style>
        .baseStyle{
                margin-top: 20px;
                margin-left: 120px;
                margin-right: 120px;
        }
        #outerPanel{
            margin-top: 30px;
            margin-left: 500px;
            margin-right: 500px;
            padding-bottom: 50px;
        }
        .padd{
            margin-left: 30px;
        }
    </style>

        <div class="panel panel-default" id="outerPanel">
            <div class="panel-body">
                <div class="baseStyle">
                    {% for c in students %}
                    <li class="list-group-item">
                            <div class="padd">
                                <a href="{% url 'campus_admin:result_add' pk4=pk4 pk=c.studentId.student_id pk1=pk1 pk2=pk2 pk3=c.courseNo.courseNo %}"> {{ c.courseNo.courseNo }}</a> <br>
                            </div>
                    </li>

                {% endfor %}

                </div>
            </div>
        </div>

{% endblock %}

register/register/campus_admin/templates/campus_admin/fee_receipt_view.html
{% extends 'student_view.html' %}
{% load staticfiles %}
{% load mathfilters %}
{% block extend %}

    <style>
        .temp{
            margin-top: 50px;
            padding:100px;

        }
        th{
            border-top:2px solid black;
            border-bottom: 2px solid black;
            color: #447e9b;
        }
        td{
             border-bottom: 2px solid black;
        }
    </style>

    <h1 style="margin-left: 600px;"> <strong> Fee Details </strong>  </h1>

<table border="1" align="center" colspan="2" width="80%" class="temp">
   <tr>
         <th width="40%" style="text-align:center;"> <strong> SemesterNo </strong> </th>
         <th width="30%" style="text-align:center;"> <strong>  Receipt No </strong> </th>
         <th width="30%" style="text-align:center;"> <strong> Status </strong> </th>

   </tr>

   <tr>
        <td width="40%" align="center">{{ pk2 }}</td>
        <td width="30%" align="center"> {{ fee.receiptId }} </td>
        <td width="30%" align="center"> {{ fee.status }}</td>


   </tr>

</table>

{% endblock extend%}

{% comment %}
 {% with ''|center:iterate as range %}
    {% for _ in  range  %}
       {% with pk2|sub:forloop.counter as pk2 %}
           <a href="{% url 'campus_admin:result_view' pk=pk pk1=pk1 pk2=pk2 pk4=pk4 %}"> Semester {{ pk2 }} Grade Card</a> <br>
       {% endwith %}
    {% endfor %}
    {% endwith %}
{% endcomment %}

register/register/campus_admin/templates/campus_admin/final_result_view.html
{% extends 'student_view.html' %}
{% load staticfiles %}
{% block extend %}
    <style>
        .baseStyle{
                margin-top: 20px;
                margin-left: 100px;
                margin-right: 120px;
        }
        #outerPanel{
              margin-top: 30px;
              margin-left: 500px;
              margin-right: 500px;
              padding-bottom: 50px;
        }
        .cmnt{
            font-size: large;
            text-align: center;
            margin-top: 200px;
        }
    </style>

        {% if value == 0 %}
            <p class="cmnt"> <strong> Nothing to Show </strong> </p>
        {% else %}
            <div class="panel panel-default" id="outerPanel">
                <div class="panel-body">
                    <div class="baseStyle">
                        {% block matter %}
                        {% with ''|center:value as range %}
                {% for _ in  range  %}
                   {% with 0|add:forloop.counter  as pk2 %}
                      <li class="list-group-item">
                        <div class="padd">
                            <a href="{% url 'campus_admin:result_view' pk=pk pk1=pk1 pk2=pk2 pk4=pk4 %}"> Semester {{ pk2 }} Grade Card</a> <br>
                        </div>
                      </li>
                   {% endwith %}
                {% endfor %}
                {% endwith %}
                        {% endblock matter%}

                    </div>
                </div>
            </div>
        {% endif %}
{% endblock extend%}

register/register/campus_admin/templates/campus_admin/homepage.html
{% extends 'campus_admin/base.html' %}


{% block body %}
     <style>
        .homeStyle{

	            margin-top: 100px;
                margin-left: 470px;
        }

    </style>

    <div class="homeStyle">
             <a href="{% url 'campus_admin:fee_receipt' %}" class="btn btn-info" role="button"> Fee Receipt</a> &nbsp;
             <a href="{% url 'campus_admin:result' %}" class="btn btn-info" role="button"> Result</a> &nbsp;
             <a href="{% url 'campus_admin:add_faculty' %}" class="btn btn-info" role="button"> Add Faculty</a> &nbsp;
             <a href="{% url 'campus_admin:add_course' %}" class="btn btn-info" role="button"> Add Courses</a> &nbsp;
    </div>



{% endblock %}

register/register/campus_admin/templates/campus_admin/range.html
@register.filter(name='range')
{% def filter_range(start, end): %}
     {% return range(start, end) %}

register/register/campus_admin/templates/campus_admin/result_base.html
{% extends 'campus_admin/base.html' %}

{% block body %}
    <style>
        .baseStyle{
                margin-top: 20px;
                margin-left: 170px;
        }
        #outerPanel{
              margin-top: 30px;
              margin-left: 500px;
              margin-right: 500px;
              padding-bottom: 50px;
        }
    </style>

        <div class="panel panel-default" id="outerPanel">
            <div class="panel-body">
                <div class="baseStyle">
                    {% block matter %}
                    {% for i in batches %}
                          <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                    {{ i.batch }} <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li> <a href="{% url 'campus_admin:result_base' pk=i.batch pk4='CS'%}">CS </a></li>
                                    <li> <a href="{% url 'campus_admin:result_base' pk=i.batch pk4='IT'%}">IT </a></li>
                                </ul>
                          </div>
                      <br>
                    {% endfor %}
                    {% endblock matter%}

                </div>
            </div>
        </div>

{% endblock %}

register/register/campus_admin/templates/campus_admin/semester_View_result.html
{% extends 'campus_admin/base.html' %}

{% load mathfilters %}
{% block body %}
    <style>
        .baseStyle{
                margin-top: 20px;
                margin-left: 120px;
                margin-right: 120px;
        }
        #outerPanel{
            margin-top: 30px;
            margin-left: 500px;
            margin-right: 500px;
            padding-bottom: 50px;
        }
        .padd{
            margin-left: 30px;
        }
    </style>

        <div class="panel panel-default" id="outerPanel">
            <div class="panel-body">
                <div class="baseStyle">
                    {% with ''|center:value as range %}
                        {% for _ in  range  %}
                        {% with 0|add:forloop.counter  as pk2 %}
                           <li class="list-group-item">
                             <div class="padd">
                                <a href="{% url 'campus_admin:course_list' pk=pk pk1=pk1 pk2=pk2 pk4=pk4 %}"> Semester {{ pk2 }}</a> <br>
                             </div>
                           </li>
                   {% endwith %}
                {% endfor %}
                {% endwith %}

                </div>
            </div>
        </div>

{% endblock %}

register/register/campus_admin/templates/campus_admin/successful_fee_receipt_update.html
{% extends 'campus_admin/base.html' %}

{% block body %}

    <style>
        .baseStyle{
                margin-top: 20px;
                margin-left: 190px;
                margin-right: 120px;
        }
        #outerPanel{
            margin-top: 30px;
            margin-left: 450px;
            margin-right: 400px;
            padding-bottom: 50px;
        }
        .temp{
            margin-left: -120px;
            margin-bottom: 20px;
        }

    </style>

        <div class="panel panel-default" id="outerPanel">
            <div class="panel-body">
                <div class="baseStyle">

                      <p class="temp"> <strong> Successfully done </strong> </p>
	                  <a href="{% url 'campus_admin:index' %}" class="done"> Return to Home </a> <br>
                      <a href="{% url 'campus_admin:fee_receipt_base' pk4=pk4 pk=pk1 %}" class="done" > Return to Student Page</a> <br>
                      <a href="{% url 'campus_admin:fee_receipt' %}" class="done" > Return to Batch</a>

                </div>
            </div>
        </div>

{% endblock %}

register/register/campus_admin/templates/campus_admin/successful_result_update.html
{% extends 'campus_admin/base.html' %}


{% block body %}
    <style>
        .baseStyle{
                margin-top: 20px;
                margin-left: 190px;
                margin-right: 120px;
        }
        #outerPanel{
            margin-top: 30px;
            margin-left: 500px;
            margin-right: 500px;
            padding-bottom: 50px;
        }
        .padd{
            margin-left: 30px;
        }
        .temp{
            margin-left: -50px;
        }
    </style>

        <div class="panel panel-default" id="outerPanel">
            <div class="panel-body">
                <div class="baseStyle">
                   	<p class="temp"> <strong> Successfully done </strong> </p>
                    <a href="{% url 'campus_admin:index' %}" class="done"> Return to Home </a> <br>
                    <a href="{% url 'campus_admin:result_base' pk4=pk4 pk=pk1 %}" class="done" > Return to Student Page</a> <br>
                    <a href="{% url 'campus_admin:result' %}" class="done" > Return to Batch</a>

                </div>
            </div>
        </div>

{% endblock %}