register/register/campus_admin/urls.py
from django.conf.urls import url
from . import views

app_name = 'campus_admin'

# For char .+ whereas for integer \d+
urlpatterns=[

    url(r'^$', views.index, name='index'),

    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/(?P<pk3>.+)/success/$', views.success_result,
        name='success_result'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/success/$', views.success_fee_receipt,
        name='success_fee_receipt'),

    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/course_list/$', views.course_list,
        name='course_list'),
    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/$', views.result_view, name='result_view'),
    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/view/$', views.final_result_view, name='final_result_view'),

    # url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/add_grade/$',views.add_grade,name='add_grade'),
    # url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/(?P<pk3>.+)/result_update/$', views.result_update,
    #   name='result_update'),
    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/(?P<pk3>.+)/result_add/$', views.result_add,
        name='result_add'),
    url(r'^result/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/$', views.sem_view_result, name='sem_view_result'),
    url(r'^result/(?P<pk4>.+)/(?P<pk>.+)/$', views.result_base, name='result_base'),
    url(r'^result/add_course/$', views.add_course, name='add_course'),
    url(r'^add_faculty/$', views.add_faculty, name='add_faculty'),
    url(r'^success/$', views.success, name='success'),
    # url(r'^result/(?P<pk5>.+)/add_semester/$',views.add_semester,name='add_semester'),
    url(r'^result/$', views.result, name='result'),
    url(r'^registration/', views.registration, name='registration'),

    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/$', views.fee_receipt_view,
        name='fee_receipt_view'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/view/$', views.final_fee_receipt_view,
        name='final_fee_receipt_view'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/(?P<pk2>\d+)/fee_receipt_add/$', views.fee_receipt_add,
        name='fee_receipt_add'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk1>.+)/(?P<pk>\d+)/$', views.sem_view_fee, name='sem_view_fee'),
    url(r'^fee_receipt/(?P<pk4>.+)/(?P<pk>.+)/$', views.fee_receipt_base, name='fee_receipt_base'),
    url(r'^fee_receipt/$', views.fee_receipt, name='fee_receipt'),

]

register/register/course/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.views.generic import TemplateView

app_name = 'course'
from .views import (course_list_of_faculty, course_detail_view, course_material_upload,
                    files_list, assignment_material_upload, assignment_files_list)
from register.announcements.views import announcement_upload, AnnouncementView
from register.faculty.views import student_assignment_submission_view

urlpatterns = [
    url(r'^course-list/$', course_list_of_faculty, name='course_list_of_faculty'),
    url(r'^(?P<course_no>.+)/assignment/upload/$', assignment_material_upload, name='assignment_material_upload'),
    url(r'^(?P<course_no>.+)/assignment-submission/(?P<assignment_id>.+)/$', student_assignment_submission_view, name='student_assignment_submission_view'),
    url(r'^(?P<course_no>.+)/assignment/files_list/$', assignment_files_list, name='assignment_material_view'),
    url(r'^(?P<course_no>.+)/course-material/upload/$', course_material_upload, name='course_material_upload'),
    url(r'^(?P<course_no>.+)/announcements/upload/$', announcement_upload, name='announcement_upload'),
    url(r'^(?P<course_no>.+)/announcements/view/$', AnnouncementView.as_view(), name='announcement_view'),
    url(r'^(?P<course_no>.+)/course-material/files_list/$', files_list, name='course_material_view'),
    url(r'^course-list/(?P<course_no>.+)/$', course_detail_view, name='course_detail_view'),
]

register/register/qa/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.QuestionIndexView.as_view(), name='qa_index'),

    url(r'^question/(?P<pk>\d+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/(?P<pk>\d+)/(?P<slug>[-_\w]+)/$',
        views.QuestionDetailView.as_view(), name='qa_detail'),

    url(r'^question/answer/(?P<answer_id>\d+)/$',
        views.AnswerQuestionView.as_view(), name='qa_answer_question'),

    url(r'^question/close/(?P<question_id>\d+)/$',
        views.CloseQuestionView.as_view(), name='qa_close_question'),

    url(r'^new-question/$', views.CreateQuestionView.as_view(),
        name='qa_create_question'),

    url(r'^edit-question/(?P<question_id>\d+)/$',
        views.UpdateQuestionView.as_view(),
        name='qa_update_question'),

    url(r'^answer/(?P<question_id>\d+)/$',
        views.CreateAnswerView.as_view(), name='qa_create_answer'),

    url(r'^answer/edit/(?P<answer_id>\d+)/$',
        views.UpdateAnswerView.as_view(), name='qa_update_answer'),



    url(r'^comment-answer/(?P<answer_id>\d+)/$',
        views.CreateAnswerCommentView.as_view(),
        name='qa_create_answer_comment'),

    url(r'^comment-question/(?P<question_id>\d+)/$',
        views.CreateQuestionCommentView.as_view(),
        name='qa_create_question_comment'),

    url(r'^comment-question/edit/(?P<comment_id>\d+)/$',
        views.UpdateQuestionCommentView.as_view(),
        name='qa_update_question_comment'),

    url(r'^comment-answer/edit/(?P<comment_id>\d+)/$',
        views.UpdateAnswerCommentView.as_view(),
        name='qa_update_answer_comment'),

    url(r'^search/$', views.QuestionsSearchView.as_view(), name='qa_search'),

    url(r'^tag/(?P<tag>[-\w]+)/$',
        views.QuestionsByTagView.as_view(), name='qa_tag'),

    url(r'^markdown/', include('django_markdown.urls')),

    url(r'hitcount/', include('hitcount.urls', namespace='hitcount')),

]

register/register/qaforum/urls.py
from django.conf.urls import include, url

from . import views

urlpatterns = [
    url(r'^$', views.QaQuestionIndexView.as_view(), name='qaforum_index'),

    url(r'^question/(?P<pk>\d+)/$',
        views.QaQuestionDetailView.as_view(), name='qaforum_detail'),

    url(r'^question/(?P<pk>\d+)/(?P<slug>[-_\w]+)/$',
        views.QaQuestionDetailView.as_view(), name='qaforum_detail'),

    url(r'^question/answer/(?P<answer_id>\d+)/$',
        views.QaAnswerQuestionView.as_view(), name='qaforum_answer_question'),

    url(r'^question/close/(?P<question_id>\d+)/$',
        views.QaCloseQuestionView.as_view(), name='qaforum_close_question'),

    url(r'^new-question/$', views.QaCreateQuestionView.as_view(),
        name='qaforum_create_question'),

    url(r'^edit-question/(?P<question_id>\d+)/$',
        views.QaUpdateQuestionView.as_view(),
        name='qaforum_update_question'),

    url(r'^answer/(?P<question_id>\d+)/$',
        views.QaCreateAnswerView.as_view(), name='qaforum_create_answer'),

    url(r'^answer/edit/(?P<answer_id>\d+)/$',
        views.QaUpdateAnswerView.as_view(), name='qaforum_update_answer'),



    url(r'^comment-answer/(?P<answer_id>\d+)/$',
        views.QaCreateAnswerCommentView.as_view(),
        name='qaforum_create_answer_comment'),

    url(r'^comment-question/(?P<question_id>\d+)/$',
        views.QaCreateQuestionCommentView.as_view(),
        name='qaforum_create_question_comment'),

    url(r'^comment-question/edit/(?P<comment_id>\d+)/$',
        views.QaUpdateQuestionCommentView.as_view(),
        name='qaforum_update_question_comment'),

    url(r'^comment-answer/edit/(?P<comment_id>\d+)/$',
        views.QaUpdateAnswerCommentView.as_view(),
        name='qaforum_update_answer_comment'),

    url(r'^search/$', views.QaQuestionsSearchView.as_view(), name='qaforum_search'),

    url(r'^tag/(?P<tag>[-\w]+)/$',
        views.QaQuestionsByTagView.as_view(), name='qaforum_tag'),

    url(r'hitcount/', include('hitcount.urls', namespace='qahitcount')),

]

register/register/student/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.views.generic import TemplateView

app_name = 'student'
from .views import (student_home_page, StudentCourseList,
                    student_course_detail_view, AnnouncementView,
                    student_assignment_files_list, course_registration_view,
                    classmates, view_profile, edit_profile,
                    files_list)

urlpatterns = [
    url(r'^$', student_home_page, name='student_home_page'),
    url(r'^courses/$', StudentCourseList.as_view(), name='student_course_list'),
    # url(r'^forum/', include('register.qaforum.urls', namespace='qaforum')),
    url(r'^classmates/$', classmates, name = 'view_classmates'),
    url(r'^profile/edit/$', edit_profile, name = 'edit_profile'),
    url(r'^profile/$', view_profile, name = 'view_profile'),
    url(r'^profile/(?P<pk>\w+)/$', view_profile, name = 'view_profile_with_pk'),

    url(r'^courses/registration/$', course_registration_view, name='course_registration_view'),
    url(r'^courses/(?P<course_no>.+)/course-material/files_list/$', files_list, name='course_material_files_list'),
    url(r'^courses/(?P<course_no>.+)/announcements/view/$', AnnouncementView.as_view(), name='announcement_view'),
    url(r'^courses/(?P<course_no>.+)/assignment/view/$', student_assignment_files_list, name='student_assignment_files_list'),
    url(r'^courses/(?P<course_no>.+)/$', student_course_detail_view, name='student_course_detail_view'),
]

register/register/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.views.static import serve

from . import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from registration.backends.hmac.views import RegistrationView
from .forms import NewRegistrationForm
from register.course.views import download, assignment_download, assignment_submission_download

urlpatterns = [
    url(r'^$', views.home, name='index'),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^campus-admin/', include('register.campus_admin.urls', namespace='campus_admin')),
    url(r'^faculty/course/', include('register.course.urls', namespace='course')),
    # url(r'^faculty/course/(?P<pk>.+)/assignment/', include('register.assignment.urls', namespace='assignment')),
    url(r'^faculty/', include('register.faculty.urls', namespace='faculty')),
    url(r'^student/courses/(?P<course_no>.+)/forum/', include('register.qa.urls', namespace='qa')),
    url(r'^faculty/courses/(?P<course_no>.+)/forum/', include('register.qa.urls', namespace='facultyqa')),
    url(r'^forum/', include('register.qaforum.urls', namespace='qaforum')),
    url(r'^student/', include('register.student.urls', namespace='student')),
    url(r'^announcements/', include('register.announcements.urls', namespace='announcements')),
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=NewRegistrationForm), name='registration_register'),
    url(r'^accounts/', include('registration.backends.hmac.urls')),
    url(r'^download/course-material/(?P<file_name>.+)$', download, name='course_material_download'),
    url(r'^download/assignment-material/(?P<file_name>.+)$', assignment_download, name='course_material_download'),
    url(r'^download/assignment-submission/(?P<file_name>.+)$', assignment_submission_download, name='course_material_download'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

if not settings.DEBUG:
    urlpatterns += [
        url(r'^staticfiles/(?P<path>.*)$', serve, {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

register/register/qa/models.py
from annoying.fields import AutoOneToOneField
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models import F
from django.utils.text import slugify
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from hitcount.models import HitCountMixin
from taggit.managers import TaggableManager
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from register.course.models import course




class Question(models.Model, HitCountMixin):
    """Model class to contain every question in the forum"""
    slug = models.SlugField(max_length=200)
    title = models.CharField(max_length=200, blank=False)
    description = MarkdownxField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    tags = TaggableManager()
    user = models.ForeignKey(User)
    closed = models.BooleanField(default=False)
    courseNo = models.ForeignKey(course, to_field='courseNo')

    def __str__(self):
        return self.title


class Answer(models.Model):
    """Model class to contain every answer in the forum and to link it
    to the proper question."""
    question = models.ForeignKey(Question)
    answer_text = MarkdownxField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    updated = models.DateTimeField('date updated', auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    answer = models.BooleanField(default=False)


    def __str__(self):  # pragma: no cover
        return self.answer_text

    class Meta:
        ordering = ['-answer', '-pub_date']




class BaseComment(models.Model):
    """Abstract model to define the basic elements to every single comment."""
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    user = models.ForeignKey(User)

    class Meta:
        abstract = True

    def __str__(self):  # pragma: no cover
        return self.comment_text


class AnswerComment(BaseComment):
    """Model class to contain the comments for the answers."""
    comment_text = MarkdownxField()
    answer = models.ForeignKey(Answer)



class QuestionComment(BaseComment):
    """Model class to contain the comments for the questions."""
    comment_text = models.CharField(max_length=250)
    question = models.ForeignKey(Question)

register/register/qa/forms.py
from django import forms
from django.conf import settings
from .models import Question



class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'description', 'tags']

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)

        try:
            settings.QA_SETTINGS['qa_description_optional']
            self.fields['description'].required = not settings.QA_SETTINGS[
                'qa_description_optional']

        except KeyError:
            pass

register/register/qa/templates/qa/base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block bar %}
{{course.course_name}}
{% endblock bar %}
{% block content %}
{% if request.user.groups.count > 0 %}
<header>
    <nav>
    <div class="navbar navbar-inverse navbar-custom" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li> <a href="/faculty/" >Home </a></li>
            <li><a href="{% url 'course:course_list_of_faculty' %}">Courses</a></li>
            <li><a href="{% url 'qaforum:qaforum_index' %}">Forum</a></li>
      <li> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
              <ul class="dropdown-menu multi-level">
                <li><a href="{% url 'auth_password_change' %}">Reset Password</a></li>
                <li><a href="{% url 'auth_logout' %}">Logout</a></li>

              </ul>
            </li>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </div>

  </nav>
</header>
{% endif %}

{% if request.user.groups.count == 0 %}
<header>
    <nav>
    <div class="navbar navbar-inverse navbar-custom" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li> <a href="/student/" >Home </a></li>
			<li> <a href="{% url 'campus_admin:final_fee_receipt_view' pk4=pk4  pk1=pk1 pk=pk %}" >Fee Details</a> </li>
			<li> <a href="{% url 'campus_admin:final_result_view' pk4=pk4  pk1=pk1 pk=pk %}" >Results </a> </li>
			<li> <a href="{% url 'student:view_classmates' %}">Classmates </a> </li>
			<li> <a href="{% url 'student:view_profile' %}" >Profile </a> </li>
      <li> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
              <ul class="dropdown-menu multi-level">
                <li><a href="{% url 'student:edit_profile' %}">Edit Profile</a></li>
                <li><a href="{% url 'auth_password_change' %}">Reset Password</a></li>
                <li><a href="{% url 'auth_logout' %}">Logout</a></li>

              </ul>
            </li>
          </ul>
        </div>
        <!--/.nav-collapse -->
      </div>
    </div>

  </nav>
</header>
{% endif %}

<div class="rows">
    <title>Discussion Forum</title>
    <link rel="icon" type="image/png" href="static/qa/icon.ico">
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>


<link href='http://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
<link href="{% static 'css/qas.css' %}" rel="stylesheet"/>

<div class="page-header">
  <a class="btn btn-lg pull-right" href="#search"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Find</a><a class="btn btn-lg pull-right" href="{% url 'qa:qa_create_question' course_no=course_no  %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Ask Question</a><h1>
    <a href="{% url 'qa:qa_index' course_no=course_no %}"><orange>Discussion Forum</orange> </a></h1>
</div>

<div class="cont">
{% if messages %}
  {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
  {% endfor %}
{% endif %}
{% block matter %}

{% endblock matter %}
 <div id="search">
   <button type="button" class="close">×</button>
   <form method="GET" action="{% url 'qa:qa_search' course_no=course_no %}">
     <input type="search" value="" name="word" placeholder="type keyword(s) here" />
     <input class="btn btn-lg" type="submit" value="Find" />
   </form>

 </div>
</div>
<hr>

</div>

<style >

        .rows{
            margin-left: 10% ;
            margin-right: 10%;
        }

		p{
		  font-family: "Lucida Sans Unicode","Lucida Grande",sans-serif;
		  font-size: 1.2rem;
		  text-align: left;
		}
		.tab{
			font-size: 20px
		}
		</style>

{% block js %}
<script>
$(function () {
  $('a[href="#search"]').on('click', function(event) {
    event.preventDefault();
    $('#search').addClass('open');
    $('#search > form > input[type="search"]').focus();
  });

  $('#search, #search button.close').on('click keyup', function(event) {
    if (event.target == this || event.target.className == 'close' || event.keyCode == 27) {
      $(this).removeClass('open');
    }
  });

});
</script>
{% endblock js %}
{%block extra_js %}{% endblock extra_js %}

{% endblock %}

register/register/qa/templates/qa/create_answer.html
{% extends 'qa/base.html' %}
{% load staticfiles %}
{% block matter %}
<div class="an">
  {% if message %}
  <strong>Enter a valid Question!</strong>
  {% endif %}

  <form method="post" action="{% block action_url %}{% url 'qa:qa_create_answer' course_no=course_no  question_id=view.kwargs.question_id %}{% endblock action_url %}">
       {% csrf_token %}
      {% for field in form  %}
         {{ field.errors }}
        <b>{{ field.label_tag }}</b> - {{ field }}

    <br>
    <br>
    {% endfor %}
      <input class="btn  btn-success" type="submit" value="Submit Answer" />
  </form>

</div>
<style >
  .an{
    padding-bottom:10%;
    padding-left: 5%;
  }
</style>
{% endblock matter %}

register/register/qa/templates/qa/create_question.html
{% extends 'qa/base.html' %}
{% load staticfiles %}

{% block matter %}
<div class="an">
  {% if message %}
  <strong>Enter a valid Question!</strong>
  {% endif %}


  <form method="post" action="{% block action_url %}{% url 'qa:qa_create_question' course_no=course_no %}{% endblock action_url %}">
   {% csrf_token %}
      {% for field in form  %}
         {{ field.errors }}
        <b>{{ field.label_tag }}</b> - {{ field }}

    <br>
    <br>
    {% endfor %}

    <input class="btn  btn-success"  type="submit" value="Submit Question" />
  </form>

</div>

<style >
  .an{
    padding-bottom: 10%;
    padding-left: 5%;
  }


</style>

{% endblock matter %}

register/register/qa/templates/qa/detail_question.html
{% extends 'qa/base.html' %}
{% load staticfiles %}

{% block matter %}


<div class="con">






<div class="jumbotron">
  <div class="row">

    <div class="col-sm-10">
      <small class="pull-right">Posted by {{ question.user.username }}, {{ question.pub_date }}</small>
      {% if user.is_authenticated and question.user == user %}<a href="{% url 'qa:qa_update_question' course_no=course_no question_id=question.id %}"><small class="pull-right">Edit &nbsp;</small></a>{% endif %}
      <h3><cool>Q: </cool>{{ question.title }}</h3>
      <h5>Description:&nbsp;{{ question.description }}</h5>
      <br>
      <p>
      {% if question.closed %}
          <p class="pull-right">This Question has been closed.</p>
      {% else %}
          <a class="btn  pull-right" style="background-color:#0f6c6b " href="{% url 'qa:qa_create_answer' course_no=course_no question_id=question.id %}" role="button"><font color=#FFFFFF>Answer this Question!</font></a><hr>
          <a class="btn  pull-right" style="background-color:#0f6c6b " href="{% url 'qa:qa_create_question_comment' course_no=course_no question_id=question.id %}" role="button"><font color=#FFFFFF>comment this Question!</font></a>
      {% endif %}
      </p>
    </div>
  </div>
</div>

{% if last_comments %}
  <h4>comments</h4>
  {% for comment in last_comments %}
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
    <p><b>{{ comment.comment_text }}</b><small>, <a href="{% url 'student:view_profile_with_pk' pk=comment.user.id %}">{{ comment.user.username }}</a> <div class="pull-right">{{ comment.pub_date }}</div></small></p>{% if comment.user == user %}<a href="{% url 'qa:qa_update_question_comment' course_no=course_no comment_id=comment.id %}" class="pull-right"><small>Edit &nbsp;</small></a>{% endif %}
    </div>
  </div>
  {% endfor %}
{% endif %}

{% if answers %}
  <h3>Answers</h3>
  <hr/>

    {% for answer in answers %}
    <div class="row">

      <div class ="col-md-9">
        <a href="{% url 'qa:qa_create_answer_comment' course_no=course_no answer_id=answer.id %}" class="pull-right"><small><span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Comment &nbsp;</small></a>
        {% if answer.user == user %}<a href="{% url 'qa:qa_update_answer' course_no=course_no answer_id=answer.id %}" class="pull-right"><small>Edit &nbsp;</small></a>{% endif %}
            <div id="ans" class="alert alert-primary" role="alert">{{ answer.answer_text }}</div>

          {% if answer.answercomment_set %}
          {% for comment in answer.answercomment_set.all %}
            <p><b>{{ comment.comment_text }}</b><small>, <a href="{% url 'student:view_profile_with_pk' pk=comment.user.id %}">{{ comment.user.username }}</a> <div class="pull-right">{{ comment.pub_date }}</div></small></p>{% if comment.user == user %}<a href="{% url 'qa:qa_update_answer_comment' course_no=course_no comment_id=comment.id %}" class="pull-right"><small>Edit &nbsp;</small></a>{% endif %}
          <hr>
          {% endfor %}
        {% endif %}
      </div>

          <div class ="col-md-2">
            {% if user.userprofile.image %}
            <a class="pull-right" href="{{ user.userprofile.image.url }}">
            <img src="{{ user.userprofile.image.url }}" align = "right" class="img-circle" alt="Cinque Terre" width="50" height="50"></a>
            {% else %}
                <img class="pull-right" src="{% static 'qa/user.png' %}"   alt="Cinque Terre" width="30" height="30">
            {% endif %}
              <p class="pull-right">- <b><a href="{% url 'student:view_profile_with_pk' pk=answer.user.id %}">{{ answer.user.username }}</a></b></p>

            </div>
            </div>
                <hr>
    {% endfor %}

{% else %}

<center><h2>This question is still not answerd, <a href="{% url 'qa:qa_create_answer' course_no=course_no question_id=question.id %}" role="button">Write answer!</a></h2></center>
{% endif %}

</div>
<style >

.con{

  padding-bottom: 10%;
}

.col-sm-10{
  padding-left: 5%
}

div {

    word-wrap: break-word
}
p{
  font-family: "Lucida Sans Unicode","Lucida Grande",sans-serif;
  font-size: 1.2rem;
  text-align: left;
}
</style>
{% endblock matter %}

{% block extra_js %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
<script>
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})
</script>
{% endblock extra_js %}

register/register/qa/templates/qa/update_answer.html
{% extends 'qa/create_answer.html' %}

{% block action_url %}
{% url 'qa:qa_update_answer' course_no=course_no answer_id=view.kwargs.answer_id %}
{% endblock action_url %}

register/register/qa/templates/qa/update_question.html
{% extends 'qa/create_question.html' %}

{% block action_url %}
{% url 'qa:qa_update_question' course_no=course_no question_id=view.kwargs.question_id %}
{% endblock action_url %}